name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: build-mac
        id: first
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-linux
        if: matrix.os == 'ubuntu-latest' && steps.first.outcome == 'success'
        run: npm run build:linux

      - name: build-win
        if: matrix.os == 'windows-latest' && steps.first.outcome == 'success'
        run: npm run build:win
