name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  create-tag:
    name: Create Git Tag from package.json
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get version from package.json
        id: version
        run: |
          echo "tag=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create GitHub Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.version.outputs.tag }}
          git push origin ${{ steps.version.outputs.tag }}

  build:
    name: Build app (${{ matrix.os }})
    needs: create-tag
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build with Electron Builder
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
