name: Create tag

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get version from package.json
        id: version
        run: echo "TAG_NAME=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create and Push Tag
        run: |
          git tag ${{ steps.version.outputs.TAG_NAME }}
          git push origin ${{ steps.version.outputs.TAG_NAME }}
